### PR TITLE
Font icons colors are edited programmatically

### PR DESCRIPTION
**Pull request by kadyEG**
Editing font icons color using `setTextColor(int color)`

### CODE REVIEW

**Comment by medyo** [comment]
Looks cool, however it'll be more interesting if you could also add a new method to change icon color. In case of someone needs different color than TextColor.

**Comment by kadyEG** [comment]
for sure but will need more effort to handle the icons brought from resources (non font icons)

will do it btw even if not fully implemented , can be added on development branch

**Comment by medyo** [comment]
Just ignore Icons from resources, just focus on Font Icons. the variables to check are 
`mIconResource` and `mIconPosition`

**Comment by kadyEG** [comment]
you mean checking those variables for resource icons ?

Btw positioning will not make problems with icon color for the font icons I think

**Comment by medyo** [comment]
I mean checking those variables just to know which type is used (from resource or font). Because applying color on a resource icon will not take an effect. You can follow that commit : 11c329030a9fd6bd65b117c348790c2b4524fefd to implement that new method setIconColor()

**Comment by kadyEG** [comment]
@medyo review the changes now

**Comment by medyo** [comment]
Looks cool :+1: Thanks for your contribution

**Pull request merged**
