### PR TITLE
If user wanna use system font

### PR DESCRIPTION
**Pull request by Haegon**
"robotoregular" font in the "Fancy button" did not go with system font of "TextView". So I put the option for button to use system font.

### CODE REVIEW

**Comment by medyo** [comment]
Hi @Haegon,

Thank your for your contribution, I'll check your code and merge it as soon as possibe

**Comment by Haegon** [comment]
How is it going?

**Comment by F0RIS** [comment]
UP

**Comment by medyo** [comment]
Merged, Thank you @Haegon 👍

**Pull request merged**
