### PR TITLE
Fix textsize fonticonsize

### PR DESCRIPTION
**Pull request by squeeish**
Ref #20: Fixed text size and fonticon size xml attributes. Fonticon preview in IDE also changes according to size set.

### CODE REVIEW

**Comment by medyo** [comment]
Perfect, I'll review it as soon as possible.

Thanks @squeeish

**Comment by medyo** [comment]
Hi @squeeish, 
Could you refactor the code, I saw many duplicated lines for the same feature, I'd recommend to create new static functions to convert `px` values to`px` and vise versa (something like PxToSP ...) . 
I think a new `Utils` class will be better to hold these new functions.

What do you think ?

**Comment by squeeish** [comment]
Sure, I'll take a look into it. Will take some time though as I'm busy nowadays. Also, I'm kind of a noob :smile:

**Comment by squeeish** [comment]
@medyo I've made the changes.

**Comment by squeeish** [comment]
@medyo, done!

**Comment by medyo** [comment]
Thanks @squeeish for your contribution.

Well done :+1:

**Comment by medyo** [comment]
@squeeish oops, 
* we missed the right unit, we should use Sp unit instead of Dp. Could you fix it ?
* Make sure you implement the converter also for Fancybuttons setters like `setTextSize(int)`
* Please update the sample project too.

Thanks

**Pull request merged**
