### PR TITLE
Adding Ghost button

### LINKED ISSUE #15: Hollow buttons focus color
If I have a hollow button ( With transparent background and a border ) ... the focus color colors the whole body , it could be tweaked to change the border only

### PR DESCRIPTION
**Pull request by abdelrahman-elkady**
Implementation of Ghost buttons ( Hollow with border ) .. this fixes #15

### CODE REVIEW

**Comment by medyo** [comment]
Could you edit the readme and add some samples ?

**Comment by abdelrahman-elkady** [comment]
Ok , I'll try to make it today

**Comment by abdelrahman-elkady** [comment]
Added Examples , Check now

**Comment by medyo** [comment]
Looks correct, Thanks for the contribution @abdelrahman-elkady

**Pull request merged**
